name: Update Submodules

on:
  schedule:
    - cron: "*/5 * * * *"  # Проверка каждые 10 минут
  workflow_dispatch:       # Добавлен ручной запуск

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Включить подмодули

      - name: Update Submodules
        run: |
          git submodule update --remote
          git add .
          git commit -m "Автоматическое обновление подмодулей" || echo "No changes"
          git push
