name: Update Submodules

on:
  schedule:
    - cron: "*/5 * * * *"  # Запуск каждые 10 минут
  workflow_dispatch:       # Ручной запуск

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  # Использование токена для работы с приватными репозиториями
          submodules: true                # Включить подмодули
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Submodules
        run: |
          git submodule update --remote
          git add .
          git commit -m "Автоматическое обновление подмодулей" || echo "No changes to commit"
          git push origin master